### ISSUE TITLE
Issue with UIL place holder

### ISSUE THREAD

**Issue by boojtran** [pungrue26/SelectableRoundedImageView#6]
I have a problem with Universal Image Loader's image place holder, when i set a drawable (a shape with solid color) as image place holder and imageview's backgroud is transparent or white, its look like in image. Please fix!

![roundimageview_err](https://cloud.githubusercontent.com/assets/2050235/6144791/b4df8518-b20d-11e4-8726-610b1ff80351.PNG)

**Comment by pungrue26** [comment]
Hi boojtran,

I appreciate your report, but I couldn't understand what you meant.

First of all, which type of <code>BItmapDisplayer</code> did you use? Be sure to use <code>SimpleBitmapDisplayer</code> or <code>FadeInBitmapDisplayer</code> rather than <code>RoundedBitmapDisplayer</code>(or <code>RoundedVignetteBitmapDisplayer</code>) when building DisplayImageOptions.

```java
options = new DisplayImageOptions.Builder()
                .showImageOnLoading(R.drawable.ic_stub)
                .showImageForEmptyUri(R.drawable.ic_empty)
                .showImageOnFail(R.drawable.ic_error)
                .cacheInMemory(true)
                .cacheOnDisk(true)
                .considerExifParams(true)
//              .displayer(new RoundedBitmapDisplayer(20))
//              DO NOT USE RoundedBitmapDisplayer. Use SimpleBitmapDisplayer!
                .displayer(new SimpleBitmapDisplayer())
                .build();
```

If this doesn't solve your problem, please share me your related code, so I can reproduce your problem.

Thanks,

**Comment by boojtran** [comment]
Hi pungrue26,
Thanks for your reply!

This is my DisplayImageOptions:
```
options = new DisplayImageOptions.Builder().showImageOnLoading(R.drawable.placeholder_light_blue).showImageOnFail(R.drawable.placeholder_light_blue).showImageForEmptyUri(R.drawable.placeholder_light_blue).imageScaleType(ImageScaleType.EXACTLY).cacheInMemory(true).cacheOnDisk(true).considerExifParams(true).build();
```

And this is my drawable:
```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android" >

    <solid android:color="#48b4e3" />

</shape>
```
I do not use `displayer()` option.
If I set `R.drawable.placeholder_light_blue` as backgroud of ImageView, everything ok.
Thanks!

**Comment by pungrue26** [comment]
Ok. I will  check it in this weekends.

Have a great day, and once again, I really apppreciate your report.

Joonho
2015. 2. 12. 오전 11:37에 "boojtran" <notifications@github.com>님이 작성:

**Comment by pungrue26** [comment]
Update.

I checked it, and found the phenomenon you mentioned about. Also I found the cause, but I couldn't finish solution yet. Currently I am having really busy days for my company's work, so it will take some time to resolve this issue. But I will resolve it when I have some time to do it. 

Happy Coding.:)

**Comment by boojtran** [comment]
Hi pungrue26,
Have a great day, I know you really busy but this product is very important to me, and this problem can take it down. I have never worked with graphics before so I can't fix it myself.

Your help is greatly appreciated,
BooJ Tran

**Comment by pungrue26** [comment]
Hey boojtran,

OK, first of all, if your placeholder image is just solid color like, <solid android:color="#48b4e3" />, create new png file using Photoshop or whatever tool you like, then use it, rather than xml drawable. 

Because current problem lies in inflating ShapeDrawable, and then transforming BitmapDrawable, I think it will probably work. Let me know it works or not!

Joonho
